### PR TITLE
Creating separate Git contributing file

### PR DESCRIPTION
**Pull request by jme-elliott**
README.md will become a table of contents files, with maybe an intro/summary of contributing. It will have a link to other .md files including Git Overview and ASG Studio

### CODE REVIEW

**Review by pozsa — DISMISSED** [review]

**Comment by jme-elliott** [comment]
@pozsa anything specific needed to approve this request?

**Review by pozsa — COMMENTED** [review]
`Add files via upload` doesn't really fit what's happening in this commit.

**Review by pozsa — APPROVED** [review]
Please use `squash and merge` to create one commit out of the two you have currently.
You'll have a chance to write a proper commit message. ;)

**Comment by pozsa** [comment]
closing it because of lack of activity

**Pull request closed without merging**
